# ALL_CATEGORY = [
#     "capsule",
#     "metal_nut",
#     "pill",
#     "toothbrush",
#     "transistor",
#     "wood",
#     "zipper",
#     "cable",
#     "bottle",
#     "grid",
#     "hazelnut",
#     "leather",
#     "tile",
#     "carpet",
#     "screw",
# ]
ALL_CATEGORY = ["MercedesTodayFinal","FordAug","FordW","ChanganTodayAug","Mercedes","MercedesAug","MercedesNoAug","MercedesNo","ChanganFinal","Kiapegasfinal",
            "Chevrolet","kiapegasfinal2",
            "CamryToday",
            "Generated_3",
            "Generated_6",
            "KIA_Rio",
            "Camry",
            "Generated_2",
            "Generated_5",
            "KIA_Pegas",
            "BMW",
            "Generated_1",
            "Generated_4",
            "Hyundai",
            "Try",
            "Try2",
            "Try3",
            "KIA_Rio2",
            "MercedesE300Final",
            "MercedesE300Resized",
            "KIA_Pegas2",
            "Generated_7",
            "Toyota_Innova",
            "Toyota_Innova_asoma","Camry2", "KIA_Rio3",
            "KIA_Rio4","KIA_Rio5", 'KIA_Rio33', "KIA_Rio55", 
            "Changan","ChanganAug","KIA_Pegas2","Changannewwww", 
            "FordF", "Fordmore","ChanganToday", "ChanganNoBackground","changanasmaaaggu", "MercedesNew", "MercedesNewAug","FordFasmaAgu4109000step","FordAsmaa"
        ]
RESIZE_SHAPE = [256, 256]  # width * height
NORMALIZE_MEAN = [0.485, 0.456, 0.406]
NORMALIZE_STD = [0.229, 0.224, 0.225]
